CREATE TABLE IF NOT EXISTS  USER(
    USER_MAIL NVARCHAR(50) NOT NULL PRIMARY KEY,
    USER_PSEUDO NVARCHAR(20) NOT NULL,
    USER_PASSWORD CHAR(60) NOT NULL,
    USER_HEIGHT INT, 
    USER_WEIGHT FLOAT,
    USER_BIRTHDAY DATE
);
CREATE TABLE IF NOT EXISTS  INVENTORY(
    INVENTORY_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    USER_MAIL NVARCHAR(50) NOT NULL
);
CREATE TABLE IF NOT EXISTS  PRODUCT(
    PRODUCT_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    PRODUCT_OFF_ID NVARCHAR(50), 
    PRODUCT_NAME NVARCHAR(50),
    PRODUCT_NUTRISCORE  NVARCHAR(6),
    BRAND_ID INT
);
CREATE TABLE IF NOT EXISTS  BRAND(
    BRAND_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    BRAND_OFF_ID NVARCHAR(50),
    BRAND_NAME NVARCHAR(50)
);
CREATE TABLE IF NOT EXISTS  USER_PRODUCT_INV(
    PRODUCT_ID INT NOT NULL,
    USER_MAIL NVARCHAR(50) NOT NULL,
    INVENTORY_ID INT NOT NULL 
);
ALTER TABLE INVENTORY 
ADD FOREIGN KEY (USER_MAIL) REFERENCES USER(USER_MAIL);

ALTER TABLE PRODUCT
ADD FOREIGN KEY (BRAND_ID) REFERENCES BRAND(BRAND_ID);

ALTER TABLE USER_PRODUCT_INV
ADD FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID);

ALTER TABLE USER_PRODUCT_INV
ADD FOREIGN KEY (USER_MAIL) REFERENCES USER(USER_MAIL);

ALTER TABLE USER_PRODUCT_INV
ADD FOREIGN KEY (INVENTORY_ID) REFERENCES INVENTORY(INVENTORY_ID);

ALTER TABLE BRAND 
ADD CONSTRAINT UNIQUE_BRANDNAME
UNIQUE(BRAND_NAME);

ALTER TABLE PRODUCT 
ADD CONSTRAINT UNIQUE_PRODUCT
UNIQUE(PRODUCT_OFF_ID);

ALTER TABLE user_product_inv
ADD CONSTRAINT constraint_unique 
UNIQUE (PRODUCT_ID);


